language: cpp
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # Get my folder
  - my_github=${PWD##*/}  

script: 
  # Build console test
  - qmake -qt=qt5 ArchiDAISIE.pro
  - make -s debug
  - ./ArchiDAISIE
  # cppcheck, be mild
  - cppcheck --quiet --error-exitcode=0 . 
  #- cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  - cd ..; sloccount --overhead 1 --personcost 22614 ArchiDAISIE; cd $my_github

after_success:
  - bash <(curl -s https://codecov.io/bash)
